# Use root/example as user/password credentials
version: '3.1'

volumes:
  mongodata: {}

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    # command: "--replSet replica"
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
